/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.CalcularResultados;
import Clases.ImportarDatos;
import Clases.MatrizDeDatos;
import Clases.OperacionElegida;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Gilme
 */
public class FrmAyudanteEstadistico extends javax.swing.JFrame {

    ImportarDatos Data = new ImportarDatos();
    OperacionElegida OE = new OperacionElegida();
    JFileChooser selecArchivo = new JFileChooser();
    File archivo;
    int contAccion;
    DefaultTableModel dtm;

    /**
     * Creates new form FrmAyudanteEstadistico
     */
    public FrmAyudanteEstadistico() {

        initComponents();
        Jlbl_btn_realizar_analisis.setVisible(false);
        this.contAccion = 0;
        setIconImage(getIconImage());

       

    }
    //codigo para el video

    //Icono del Programa
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Formularios/btn_images/icono_ayudante_estadistico.png"));
        return retValue;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpPanelGlobal = new javax.swing.JTabbedPane();
        JpInicio = new javax.swing.JPanel();
        Jlbl_btn_empezar = new javax.swing.JLabel();
        lbl_Titulo = new javax.swing.JLabel();
        aux = new javax.swing.JPanel();
        lbl_tutorial = new javax.swing.JLabel();
        instruccion_1 = new javax.swing.JLabel();
        instruccion_2 = new javax.swing.JLabel();
        instruccion_3 = new javax.swing.JLabel();
        instruccion_4 = new javax.swing.JLabel();
        instruccion_5 = new javax.swing.JLabel();
        instruccion_6 = new javax.swing.JLabel();
        instruccion_7 = new javax.swing.JLabel();
        instruccion_8 = new javax.swing.JLabel();
        instruccion_9 = new javax.swing.JLabel();
        instruccion_10 = new javax.swing.JLabel();
        instruccion_11 = new javax.swing.JLabel();
        instruccion_12 = new javax.swing.JLabel();
        instruccion_13 = new javax.swing.JLabel();
        JpImportarExcel = new javax.swing.JPanel();
        Jlbl_btn_Seleccionar_Archivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtDatos = new javax.swing.JTable();
        Jlbl_btn_realizar_analisis = new javax.swing.JLabel();
        Jlbl_btn_regresar_pantalla_importar = new javax.swing.JLabel();
        JpRealizarAnalisis = new javax.swing.JPanel();
        cbx_Titulos = new javax.swing.JComboBox<>();
        lbl_Columnas_Detectadas = new javax.swing.JLabel();
        lbl_seleccione_columna = new javax.swing.JLabel();
        lbl_operacion_seleccionada = new javax.swing.JLabel();
        cbx_Operacion_seleccionada = new javax.swing.JComboBox<>();
        lbl_Filas_Detectadas = new javax.swing.JLabel();
        lbl_poblacion_o_muestra = new javax.swing.JLabel();
        Jlbl_btn_regresar_pantalla_analisis = new javax.swing.JLabel();
        Jlbl_btn_mostrar_resultados_pantalla_analisis = new javax.swing.JLabel();
        cbx_poblacion_o_muestra = new javax.swing.JComboBox<>();
        JpResultados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtResultados = new javax.swing.JTable();
        Jlbl_regresar_pantalla_resultado = new javax.swing.JLabel();
        JPanel_Graficas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ayudante Estadístico - Autor: Manuel Gilmer Vilcapoma Carbajal");
        setBackground(new java.awt.Color(0, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        JpPanelGlobal.setBackground(new java.awt.Color(0, 204, 204));
        JpPanelGlobal.setBorder(new javax.swing.border.MatteBorder(null));
        JpPanelGlobal.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        JpPanelGlobal.setToolTipText("");
        JpPanelGlobal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JpPanelGlobal.setEnabled(false);

        JpInicio.setBackground(new java.awt.Color(51, 255, 204));
        JpInicio.setPreferredSize(new java.awt.Dimension(800, 551));

        Jlbl_btn_empezar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Empezar.png"))); // NOI18N
        Jlbl_btn_empezar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jlbl_btn_empezar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jlbl_btn_empezarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_btn_empezarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_btn_empezarMouseExited(evt);
            }
        });

        lbl_Titulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_Titulo.setText("¿Cómo usar Ayudante Estadístico?");

        aux.setBackground(new java.awt.Color(0, 204, 204));
        aux.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_tutorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Tutorial.gif"))); // NOI18N
        lbl_tutorial.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_tutorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        instruccion_1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        instruccion_1.setText("☺Notas sobre el programa:");

        instruccion_2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        instruccion_2.setText("♦ El archivo excel debe tener reservada");

        instruccion_3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        instruccion_3.setText("la primera fila para los titulos.");

        instruccion_4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        instruccion_4.setText("♦ Los datos del excel deben ser datos ");

        instruccion_5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        instruccion_5.setText("cuantitavos.");

        instruccion_6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        instruccion_6.setText("omo \"otros\".");

        instruccion_7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        instruccion_7.setText("♦ A los datos enteros se le agregara el ");

        instruccion_8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        instruccion_8.setText("♦ Si el dato solo se repite una vez en la");

        instruccion_9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        instruccion_9.setText("columna, sera considera en el grafico c-");

        instruccion_10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        instruccion_10.setText("un dato cuantitativo, el programa no reali-");

        instruccion_11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        instruccion_11.setText("zara ningun analisis estadístico.");

        instruccion_12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        instruccion_12.setText("\".00\" para su correcto calculo estadistico.");

        instruccion_13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        instruccion_13.setText("♦ Si uno de los datos del excel no es  ");

        javax.swing.GroupLayout auxLayout = new javax.swing.GroupLayout(aux);
        aux.setLayout(auxLayout);
        auxLayout.setHorizontalGroup(
            auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(auxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(auxLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instruccion_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instruccion_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instruccion_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instruccion_8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instruccion_9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instruccion_7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instruccion_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instruccion_12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instruccion_13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instruccion_11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instruccion_10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instruccion_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(instruccion_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(lbl_tutorial, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        auxLayout.setVerticalGroup(
            auxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, auxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_tutorial, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(auxLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(instruccion_1)
                .addGap(18, 18, 18)
                .addComponent(instruccion_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instruccion_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instruccion_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instruccion_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instruccion_8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instruccion_9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instruccion_6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instruccion_7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instruccion_12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instruccion_13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instruccion_10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instruccion_11)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JpInicioLayout = new javax.swing.GroupLayout(JpInicio);
        JpInicio.setLayout(JpInicioLayout);
        JpInicioLayout.setHorizontalGroup(
            JpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpInicioLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(lbl_Titulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(JpInicioLayout.createSequentialGroup()
                .addGroup(JpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpInicioLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(Jlbl_btn_empezar))
                    .addGroup(JpInicioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(aux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        JpInicioLayout.setVerticalGroup(
            JpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpInicioLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lbl_Titulo)
                .addGap(18, 18, 18)
                .addComponent(aux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(Jlbl_btn_empezar)
                .addGap(17, 17, 17))
        );

        JpPanelGlobal.addTab("Inicio", JpInicio);

        JpImportarExcel.setBackground(new java.awt.Color(51, 255, 204));
        JpImportarExcel.setPreferredSize(new java.awt.Dimension(800, 559));

        Jlbl_btn_Seleccionar_Archivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Seleccionar_Archivo.png"))); // NOI18N
        Jlbl_btn_Seleccionar_Archivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jlbl_btn_Seleccionar_ArchivoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_btn_Seleccionar_ArchivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_btn_Seleccionar_ArchivoMouseExited(evt);
            }
        });

        JtDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JtDatos);

        Jlbl_btn_realizar_analisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Realizar_Analisis.png"))); // NOI18N
        Jlbl_btn_realizar_analisis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jlbl_btn_realizar_analisisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_btn_realizar_analisisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_btn_realizar_analisisMouseExited(evt);
            }
        });

        Jlbl_btn_regresar_pantalla_importar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Regresar.png"))); // NOI18N
        Jlbl_btn_regresar_pantalla_importar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jlbl_btn_regresar_pantalla_importarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_btn_regresar_pantalla_importarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_btn_regresar_pantalla_importarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JpImportarExcelLayout = new javax.swing.GroupLayout(JpImportarExcel);
        JpImportarExcel.setLayout(JpImportarExcelLayout);
        JpImportarExcelLayout.setHorizontalGroup(
            JpImportarExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpImportarExcelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(JpImportarExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jlbl_btn_regresar_pantalla_importar)
                    .addGroup(JpImportarExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(JpImportarExcelLayout.createSequentialGroup()
                            .addComponent(Jlbl_btn_Seleccionar_Archivo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jlbl_btn_realizar_analisis))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        JpImportarExcelLayout.setVerticalGroup(
            JpImportarExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpImportarExcelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpImportarExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jlbl_btn_realizar_analisis, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(Jlbl_btn_Seleccionar_Archivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jlbl_btn_regresar_pantalla_importar)
                .addGap(14, 14, 14))
        );

        JpPanelGlobal.addTab("Importar Excel", JpImportarExcel);

        JpRealizarAnalisis.setBackground(new java.awt.Color(51, 255, 204));

        cbx_Titulos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lbl_Columnas_Detectadas.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Columnas_Detectadas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_Columnas_Detectadas.setText("Columnas detectadas :");

        lbl_seleccione_columna.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_seleccione_columna.setText("1. Seleccione la Columna a Analizar :");

        lbl_operacion_seleccionada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_operacion_seleccionada.setText("2. Seleccione la operación estadistica :");

        cbx_Operacion_seleccionada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbx_Operacion_seleccionada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas las operaciones", "Promedio o Media", "Mediana", "Moda", "Rango de Variación,amplitud o recorrido", "Maximo", "Minimo", "Varianza", "Desviación estándar", "Coeficiente de Variación", "Desviación Media", "Media Geometrica" }));

        lbl_Filas_Detectadas.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Filas_Detectadas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_Filas_Detectadas.setText("Filas detectadas :");

        lbl_poblacion_o_muestra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_poblacion_o_muestra.setText("3. ¿Los Datos son de una Poblacion o de una Muestra ?");

        Jlbl_btn_regresar_pantalla_analisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Regresar.png"))); // NOI18N
        Jlbl_btn_regresar_pantalla_analisis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jlbl_btn_regresar_pantalla_analisisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_btn_regresar_pantalla_analisisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_btn_regresar_pantalla_analisisMouseExited(evt);
            }
        });

        Jlbl_btn_mostrar_resultados_pantalla_analisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Mostrar_Resultados.png"))); // NOI18N
        Jlbl_btn_mostrar_resultados_pantalla_analisis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jlbl_btn_mostrar_resultados_pantalla_analisisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_btn_mostrar_resultados_pantalla_analisisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_btn_mostrar_resultados_pantalla_analisisMouseExited(evt);
            }
        });

        cbx_poblacion_o_muestra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbx_poblacion_o_muestra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Población", "Muestra" }));

        javax.swing.GroupLayout JpRealizarAnalisisLayout = new javax.swing.GroupLayout(JpRealizarAnalisis);
        JpRealizarAnalisis.setLayout(JpRealizarAnalisisLayout);
        JpRealizarAnalisisLayout.setHorizontalGroup(
            JpRealizarAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRealizarAnalisisLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Jlbl_btn_regresar_pantalla_analisis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jlbl_btn_mostrar_resultados_pantalla_analisis)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpRealizarAnalisisLayout.createSequentialGroup()
                .addGap(0, 266, Short.MAX_VALUE)
                .addGroup(JpRealizarAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Columnas_Detectadas, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Filas_Detectadas, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_seleccione_columna)
                    .addComponent(cbx_Titulos, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_operacion_seleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_Operacion_seleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_poblacion_o_muestra)
                    .addComponent(cbx_poblacion_o_muestra, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(174, 174, 174))
        );
        JpRealizarAnalisisLayout.setVerticalGroup(
            JpRealizarAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpRealizarAnalisisLayout.createSequentialGroup()
                .addGroup(JpRealizarAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JpRealizarAnalisisLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jlbl_btn_mostrar_resultados_pantalla_analisis))
                    .addGroup(JpRealizarAnalisisLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lbl_Columnas_Detectadas)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Filas_Detectadas)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_seleccione_columna)
                        .addGap(18, 18, 18)
                        .addComponent(cbx_Titulos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_operacion_seleccionada)
                        .addGap(18, 18, 18)
                        .addComponent(cbx_Operacion_seleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_poblacion_o_muestra)
                        .addGap(18, 18, 18)
                        .addComponent(cbx_poblacion_o_muestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(Jlbl_btn_regresar_pantalla_analisis)))
                .addGap(16, 16, 16))
        );

        JpPanelGlobal.addTab("Realizar Analisis", JpRealizarAnalisis);

        JpResultados.setBackground(new java.awt.Color(51, 255, 204));
        JpResultados.setPreferredSize(new java.awt.Dimension(800, 551));

        JtResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Operación Estadistica", "Resultado", "Interpretación"
            }
        ));
        jScrollPane2.setViewportView(JtResultados);
        if (JtResultados.getColumnModel().getColumnCount() > 0) {
            JtResultados.getColumnModel().getColumn(0).setMinWidth(160);
            JtResultados.getColumnModel().getColumn(0).setPreferredWidth(160);
            JtResultados.getColumnModel().getColumn(0).setMaxWidth(160);
            JtResultados.getColumnModel().getColumn(1).setMinWidth(160);
            JtResultados.getColumnModel().getColumn(1).setPreferredWidth(160);
            JtResultados.getColumnModel().getColumn(1).setMaxWidth(160);
        }

        Jlbl_regresar_pantalla_resultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Regresar.png"))); // NOI18N
        Jlbl_regresar_pantalla_resultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jlbl_regresar_pantalla_resultadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_regresar_pantalla_resultadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_regresar_pantalla_resultadoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JPanel_GraficasLayout = new javax.swing.GroupLayout(JPanel_Graficas);
        JPanel_Graficas.setLayout(JPanel_GraficasLayout);
        JPanel_GraficasLayout.setHorizontalGroup(
            JPanel_GraficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JPanel_GraficasLayout.setVerticalGroup(
            JPanel_GraficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JpResultadosLayout = new javax.swing.GroupLayout(JpResultados);
        JpResultados.setLayout(JpResultadosLayout);
        JpResultadosLayout.setHorizontalGroup(
            JpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(JPanel_Graficas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JpResultadosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Jlbl_regresar_pantalla_resultado)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JpResultadosLayout.setVerticalGroup(
            JpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanel_Graficas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jlbl_regresar_pantalla_resultado)
                .addContainerGap())
        );

        JpPanelGlobal.addTab("Resultados", JpResultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpPanelGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpPanelGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Esta función es para ser el hover en los botones
    private void Jlbl_btn_empezarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_empezarMouseEntered

        Jlbl_btn_empezar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Empezar_Hover.png")));

    }//GEN-LAST:event_Jlbl_btn_empezarMouseEntered

    private void Jlbl_btn_empezarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_empezarMouseExited
        Jlbl_btn_empezar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Empezar.png")));
    }//GEN-LAST:event_Jlbl_btn_empezarMouseExited

    private void Jlbl_btn_empezarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_empezarMouseClicked
        JpPanelGlobal.setSelectedIndex(1);
    }//GEN-LAST:event_Jlbl_btn_empezarMouseClicked

    private void Jlbl_btn_Seleccionar_ArchivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_Seleccionar_ArchivoMouseEntered
        Jlbl_btn_Seleccionar_Archivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Seleccionar_Archivo_hover.png")));
    }//GEN-LAST:event_Jlbl_btn_Seleccionar_ArchivoMouseEntered

    private void Jlbl_btn_Seleccionar_ArchivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_Seleccionar_ArchivoMouseExited
        Jlbl_btn_Seleccionar_Archivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Seleccionar_Archivo.png")));
    }//GEN-LAST:event_Jlbl_btn_Seleccionar_ArchivoMouseExited

    public void AgregarFiltro() {
        selecArchivo.setFileFilter(new FileNameExtensionFilter("Excel (*.xls)", "xls"));
        selecArchivo.setFileFilter(new FileNameExtensionFilter("Excel (*.xlsx)", "xlsx"));
    }
    private void Jlbl_btn_Seleccionar_ArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_Seleccionar_ArchivoMouseClicked

        contAccion++;
        if (contAccion == 1) {
            AgregarFiltro();
        }

        if (selecArchivo.showDialog(null, "Seleccionar archivo") == JFileChooser.APPROVE_OPTION) {
            archivo = selecArchivo.getSelectedFile();
            if (archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")) {
                JOptionPane.showMessageDialog(null,
                        Data.Importar(archivo, JtDatos) + "\n Formato ." + archivo.getName().substring(archivo.getName().lastIndexOf(".") + 1),
                        "IMPORTAR EXCEL", JOptionPane.INFORMATION_MESSAGE);
                Jlbl_btn_realizar_analisis.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Elija un formato valido.");
            }
        }

        //LLENAR LA MATRIZ DE DATOS
        int NColumnas = JtDatos.getColumnCount();
        int NFilas = JtDatos.getRowCount();

        double Datos[][] = new double[NFilas][NColumnas];
        String TitulosdeDatos[] = new String[NColumnas];
        for (int j = 0; j < NColumnas; j++) {
            for (int i = 0; i < NFilas; i++) {
                Datos[i][j] = Double.parseDouble(JtDatos.getValueAt(i, j).toString());
            }
        }

        for (int j = 0; j < NColumnas; j++) {
            TitulosdeDatos[j] = JtDatos.getColumnName(j);
        }
        Data.set_Numero_de_Filas(NFilas);
        Data.setNumero_de_columnas(NColumnas);
        Data.set_Matriz_de_datos(Datos);
        Data.setVector_de_titulos(TitulosdeDatos);


    }//GEN-LAST:event_Jlbl_btn_Seleccionar_ArchivoMouseClicked

    private void Jlbl_btn_realizar_analisisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_realizar_analisisMouseEntered
        Jlbl_btn_realizar_analisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Realizar_Analisis_Hover.png")));

    }//GEN-LAST:event_Jlbl_btn_realizar_analisisMouseEntered

    private void Jlbl_btn_realizar_analisisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_realizar_analisisMouseExited
        Jlbl_btn_realizar_analisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Realizar_Analisis.png")));

    }//GEN-LAST:event_Jlbl_btn_realizar_analisisMouseExited

    private void Jlbl_btn_realizar_analisisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_realizar_analisisMouseClicked
        lbl_Columnas_Detectadas.setText("Columnas Detectadas : " + Data.getNumero_de_columnas());
        lbl_Filas_Detectadas.setText("Filas Detectadas : " + Data.get_Numero_de_Filas());
        for (int i = 0; i < Data.getVector_de_titulos().length; i++) {
            cbx_Titulos.addItem(Data.getVector_de_titulos()[i].toString());
        }

        JpPanelGlobal.setSelectedIndex(2);

    }//GEN-LAST:event_Jlbl_btn_realizar_analisisMouseClicked

    private void Jlbl_btn_regresar_pantalla_analisisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_regresar_pantalla_analisisMouseEntered
        Jlbl_btn_regresar_pantalla_analisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Regresar_Hover.png")));

    }//GEN-LAST:event_Jlbl_btn_regresar_pantalla_analisisMouseEntered

    private void Jlbl_btn_regresar_pantalla_analisisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_regresar_pantalla_analisisMouseExited
        Jlbl_btn_regresar_pantalla_analisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Regresar.png")));
    }//GEN-LAST:event_Jlbl_btn_regresar_pantalla_analisisMouseExited

    private void Jlbl_btn_regresar_pantalla_analisisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_regresar_pantalla_analisisMouseClicked
        // TODO add your handling code here:
        cbx_Titulos.removeAllItems();
        JpPanelGlobal.setSelectedIndex(1);

    }//GEN-LAST:event_Jlbl_btn_regresar_pantalla_analisisMouseClicked

    private void Jlbl_btn_regresar_pantalla_importarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_regresar_pantalla_importarMouseEntered
        Jlbl_btn_regresar_pantalla_importar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Regresar_Hover.png")));

    }//GEN-LAST:event_Jlbl_btn_regresar_pantalla_importarMouseEntered

    private void Jlbl_btn_regresar_pantalla_importarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_regresar_pantalla_importarMouseExited
        Jlbl_btn_regresar_pantalla_importar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Regresar.png")));

    }//GEN-LAST:event_Jlbl_btn_regresar_pantalla_importarMouseExited

    private void Jlbl_btn_regresar_pantalla_importarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_regresar_pantalla_importarMouseClicked
        JpPanelGlobal.setSelectedIndex(0);
        dtm = (DefaultTableModel) JtDatos.getModel();
        for (int i = dtm.getRowCount() - 1; i >= 0; i--) {
            dtm.removeRow(i);

        }
        for (var i = dtm.getColumnCount() - 1; i >= 0; i--) {
            JtDatos.removeColumn(JtDatos.getColumnModel().getColumn(i));
        }
        Jlbl_btn_realizar_analisis.setVisible(false);

    }//GEN-LAST:event_Jlbl_btn_regresar_pantalla_importarMouseClicked

    private void Jlbl_btn_mostrar_resultados_pantalla_analisisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_mostrar_resultados_pantalla_analisisMouseEntered
        Jlbl_btn_mostrar_resultados_pantalla_analisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Mostrar_Resultados_Hover.png")));

    }//GEN-LAST:event_Jlbl_btn_mostrar_resultados_pantalla_analisisMouseEntered

    private void Jlbl_btn_mostrar_resultados_pantalla_analisisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_mostrar_resultados_pantalla_analisisMouseExited
        Jlbl_btn_mostrar_resultados_pantalla_analisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Mostrar_Resultados.png")));

    }//GEN-LAST:event_Jlbl_btn_mostrar_resultados_pantalla_analisisMouseExited

    private void Jlbl_btn_mostrar_resultados_pantalla_analisisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_btn_mostrar_resultados_pantalla_analisisMouseClicked
        int NColumnas = JtDatos.getColumnCount();
        int NFilas = JtDatos.getRowCount();
        double Datos[][] = new double[NFilas][NColumnas];
        String TitulosdeDatos[] = new String[NColumnas];
        for (int j = 0; j < NColumnas; j++) {
            for (int i = 0; i < NFilas; i++) {
                Datos[i][j] = Double.parseDouble(JtDatos.getValueAt(i, j).toString());
            }
        }

        for (int j = 0; j < NColumnas; j++) {
            TitulosdeDatos[j] = JtDatos.getColumnName(j);
        }
        OE.set_Numero_de_Filas(NFilas);
        OE.setNumero_de_columnas(NColumnas);
        OE.set_Matriz_de_datos(Datos);
        OE.setVector_de_titulos(TitulosdeDatos);
        OE.setColumna_seleccionada(cbx_Titulos.getSelectedIndex());
        OE.setOperacion_elegida(cbx_Operacion_seleccionada.getSelectedIndex());
        OE.setPoblacion_o_muestra(cbx_poblacion_o_muestra.getSelectedIndex());
        OE.setVector_operativo(cbx_Titulos.getSelectedIndex());
        //Agregar Data a la tabla resultado

        dtm = (DefaultTableModel) JtResultados.getModel();

        if (cbx_Operacion_seleccionada.getSelectedIndex() != 0) {
            dtm.addRow(OE.devolver_resultado());
        } else {

            for (int i = 1; i < 12; i++) {
                OE.setOperacion_elegida(i);
                dtm.addRow(OE.devolver_resultado());
            }
        }
        //Hacer el Grafico Circular
        DefaultPieDataset datos_a_graficar = new DefaultPieDataset();
        int[] vector_de_frecuencias = new int[OE.getVector_operativo().length];
        int contador = 0;
        for (int i = 0; i < OE.getVector_operativo().length; i++) {
            for (int j = 0; j < OE.getVector_operativo().length; j++) {
                if (OE.getVector_operativo()[i] == OE.getVector_operativo()[j]) {
                    contador++;
                }
            }
            vector_de_frecuencias[i] = contador;
            contador = 0;
        }
        int Variable_Otros = 0;
        for (int i = 0; i < OE.getVector_operativo().length; i++) {
            if (vector_de_frecuencias[i] == 1) {
                Variable_Otros++;
            } else {
                datos_a_graficar.setValue("[" + OE.getVector_operativo()[i] + "]", vector_de_frecuencias[i]);
            }
        }
        datos_a_graficar.setValue("Otros", Variable_Otros);

        JFreeChart grafico_circular = ChartFactory.createPieChart3D(
                OE.getVector_de_titulos()[cbx_Titulos.getSelectedIndex()],
                datos_a_graficar,
                true,
                true,
                false
        );
        ChartPanel panel = new ChartPanel(grafico_circular);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(400, 273));
        JPanel_Graficas.setLayout(new BorderLayout());
        JPanel_Graficas.add(panel, BorderLayout.NORTH);
        pack();
        repaint();
        JpPanelGlobal.setSelectedIndex(3);
    }//GEN-LAST:event_Jlbl_btn_mostrar_resultados_pantalla_analisisMouseClicked

    private void Jlbl_regresar_pantalla_resultadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_regresar_pantalla_resultadoMouseExited
        Jlbl_regresar_pantalla_resultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Regresar.png")));
    }//GEN-LAST:event_Jlbl_regresar_pantalla_resultadoMouseExited

    private void Jlbl_regresar_pantalla_resultadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_regresar_pantalla_resultadoMouseEntered
        Jlbl_regresar_pantalla_resultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/btn_images/Img_Btn_Regresar_Hover.png")));
    }//GEN-LAST:event_Jlbl_regresar_pantalla_resultadoMouseEntered

    private void Jlbl_regresar_pantalla_resultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_regresar_pantalla_resultadoMouseClicked

        JpPanelGlobal.setSelectedIndex(2);
        JPanel_Graficas.removeAll();
        JPanel_Graficas.repaint();
        dtm = (DefaultTableModel) JtResultados.getModel();
        if (cbx_Operacion_seleccionada.getSelectedIndex() != 0) {

            dtm.removeRow(0);

        } else {

            for (int i = 10; i >= 0; i--) {
                dtm.removeRow(i);
            }
        }
    }//GEN-LAST:event_Jlbl_regresar_pantalla_resultadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAyudanteEstadistico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAyudanteEstadistico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAyudanteEstadistico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAyudanteEstadistico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAyudanteEstadistico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel_Graficas;
    private javax.swing.JLabel Jlbl_btn_Seleccionar_Archivo;
    private javax.swing.JLabel Jlbl_btn_empezar;
    private javax.swing.JLabel Jlbl_btn_mostrar_resultados_pantalla_analisis;
    private javax.swing.JLabel Jlbl_btn_realizar_analisis;
    private javax.swing.JLabel Jlbl_btn_regresar_pantalla_analisis;
    private javax.swing.JLabel Jlbl_btn_regresar_pantalla_importar;
    private javax.swing.JLabel Jlbl_regresar_pantalla_resultado;
    private javax.swing.JPanel JpImportarExcel;
    private javax.swing.JPanel JpInicio;
    private javax.swing.JTabbedPane JpPanelGlobal;
    private javax.swing.JPanel JpRealizarAnalisis;
    private javax.swing.JPanel JpResultados;
    private javax.swing.JTable JtDatos;
    private javax.swing.JTable JtResultados;
    private javax.swing.JPanel aux;
    public javax.swing.JComboBox<String> cbx_Operacion_seleccionada;
    public javax.swing.JComboBox<String> cbx_Titulos;
    private javax.swing.JComboBox<String> cbx_poblacion_o_muestra;
    private javax.swing.JLabel instruccion_1;
    private javax.swing.JLabel instruccion_10;
    private javax.swing.JLabel instruccion_11;
    private javax.swing.JLabel instruccion_12;
    private javax.swing.JLabel instruccion_13;
    private javax.swing.JLabel instruccion_2;
    private javax.swing.JLabel instruccion_3;
    private javax.swing.JLabel instruccion_4;
    private javax.swing.JLabel instruccion_5;
    private javax.swing.JLabel instruccion_6;
    private javax.swing.JLabel instruccion_7;
    private javax.swing.JLabel instruccion_8;
    private javax.swing.JLabel instruccion_9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Columnas_Detectadas;
    private javax.swing.JLabel lbl_Filas_Detectadas;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JLabel lbl_operacion_seleccionada;
    private javax.swing.JLabel lbl_poblacion_o_muestra;
    private javax.swing.JLabel lbl_seleccione_columna;
    private javax.swing.JLabel lbl_tutorial;
    // End of variables declaration//GEN-END:variables
}
